version: '3'
services:
  redis:
    image: redis/redis-stack:7.2.0-v3
    ports:
      - '6379:6379' #RedisStackServer
      - '8001:8001' #RedisInsight
    volumes:
      - ./data/:/data
#    env_file:
#      - ./esc_db/env.db
